<robot name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_length" value="0.02" /> <!--厚度x-->
    <xacro:property name="camera_width" value="0.05" /> <!--厚度y-->
    <xacro:property name="camera_heigh" value="0.05" /> <!--高度z-->
    <xacro:property name="camera_mass" value="0.01" />
    <xacro:property name="joint_camera_x" value="0.08" /> 
    <xacro:property name="joint_camera_y" value="0" /> 
    <xacro:property name="joint_camera_z" value="${baselink_length/2+camera_heigh/2}" /> 
    <link name="camera">
            <visual>
                <geometry>
                    <box size="${camera_length} ${camera_width} ${camera_heigh}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="camera_color">
                    <color rgba="0 0 1 1" />
                </material>
            </visual>
               <!--设置碰撞参数-->
           <collision>
               <geometry>
                    <box size="${camera_length} ${camera_width} ${camera_heigh}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
           </collision>
              <!--设置惯性矩阵-->
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_heigh}"/>
        </link>
        <!--设置Gazeor中的颜色-->
        <gazebo reference="camera">
            <material>Gazebo/Blue</material>
        </gazebo>
    <joint name="camerabase" type="fixed">
            <parent link="base_link"  />
            <child link="camera" />
            <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0 0 0" />
    </joint>
</robot>